name: Client
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Clone repo to container
      - name: Clone repo
        uses: actions/checkout@v2

      # Build static client site
      - name: Build client
        working-directory: ./client
        run: npm install && npm run build

      # Share artifact to share for deploy step
      - name: Share client artifact
        uses: actions/upload-artifact@v3
        with:
          name: client
          path: ./client/dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Get shared client artifact from build step
      - name: Get client artifact
        uses: actions/download-artifact@v3
        with:
          name: client

      # Set AWS creds as secrets
      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # Copy files from artifact to S3
      - name: Upload static site to S3
        run: aws s3 sync . s3://clicktracker-static-site --delete
