name: Infra
on:
  workflow_call:
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      # Clone repo to container
      - name: Clone repo
        uses: actions/checkout@v2

      # Initialize Terraform module
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.5

      # Check formatting/style
      - name: Terraform fmt check
        run: terraform fmt -check -diff ./tf
  plan_and_apply:
    name: Plan & Apply
    runs-on: ubuntu-latest
    needs: lint
    steps:
      # Clone repo to container
      - name: Clone repo
        uses: actions/checkout@v2

      # Initialize Terraform module
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.5

      # Set AWS creds as secrets
      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # Init working directory for Terraform
      - name: Terraform init
        working-directory: ./tf
        run: terraform init -input=false

      # Detect differences between plan and infra
      - name: Terraform plan
        working-directory: ./tf
        run: terraform plan -input=false -no-color

      # Apply plans to infra
      - name: Terraform apply
        working-directory: ./tf
        run: terraform apply
